lib/fire_watch_web/router.ex
defmodule FireWatchWeb.Router do
  use FireWatchWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {FireWatchWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", FireWatchWeb do
    pipe_through :browser

    live "/", DashboardLive, :index
    live "/fires", FireLive.Index, :index
    live "/fires/new", FireLive.Index, :new
    live "/fires/:id/edit", FireLive.Index, :edit

    live "/fires/:id", FireLive.Show, :show
    live "/fires/:id/show/edit", FireLive.Show, :edit
  end

  # Other scopes may use custom stacks.
  # scope "/api", FireWatchWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: FireWatchWeb.Telemetry
    end
  end
end

lib/fire_watch_web/views/layout_view.ex
defmodule FireWatchWeb.LayoutView do
  use FireWatchWeb, :view
end

lib/fire_watch_web/templates/layout/app.html.eex
<main role="main" class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/fire_watch_web/templates/layout/live.html.leex
<main role="main" class="pt-12 max-w-5xl container mx-auto">
  <p class="alert alert-info mt-2" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger mt-2" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/fire_watch_web/templates/layout/root.html.leex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "FireWatch", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer phx-track-static type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body class="bg-gray-100">
    <header class="bg-white shadow-md fixed w-full">
      <section class="h-12 container max-w-5xl mx-auto flex items-center justify-between space-x-1">
        <div class="flex items-center">
          <%= live_redirect to: Routes.dashboard_path(@conn, :index), class: "flex items-center space-x-1" do %>
            <img src="<%= Routes.static_path(@conn, "/images/firewatch.png") %>" class="h-8" alt="FireWatch Logo"/>
            <h3 class="leading-none text-yellow-700">FireWatch</h3>
          <% end %>
          <ul class="flex items-center space-x-1 px-2">
            <li>
              <%= live_redirect to: Routes.dashboard_path(@conn, :index), class: "btn-secondary btn-md" do %>
                Dashboard
              <% end %>
              <%= live_redirect to: Routes.fire_index_path(@conn, :index), class: "btn-secondary btn-md" do %>
                Reports
              <% end %>
            </li>
          </ul>
        </div>
        <nav role="navigation">
          <ul class="flex items-center space-x-1">
            <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
              <li><%= link "Live Dashboard", to: Routes.live_dashboard_path(@conn, :home), class: "btn-secondary btn-md" %></li>
            <% end %>
          </ul>
        </nav>
      </section>
    </header>
    <%= @inner_content %>
  </body>
</html>